WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

FPS_LIMIT = 60

PHEROMONE_DROP_INTERVAL = FPS_LIMIT // 5
PHEROMONE_UPDATE_INTERVAL = FPS_LIMIT // 2
ANT_TURN_INTERVAL = FPS_LIMIT // 10
ANT_COLLISION_CHECK_INTERVAL = FPS_LIMIT // 10

# MAX_ANTS = 200
MAX_ANTS_PER_COLONY = 30