WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

# FPS_LIMIT = 10
# FPS_LIMIT = 40
FPS_LIMIT = 60
# FPS_LIMIT = 100

PH_MAX_STRENGTH = 10
ANT_TURN_INTERVAL = FPS_LIMIT // 10
PH_DROP_INTERVAL = FPS_LIMIT // 10
# ANT_TURN_INTERVAL = FPS_LIMIT // 20
# PH_DROP_INTERVAL = FPS_LIMIT // 20
PH_DECAY_INTERVAL = FPS_LIMIT // 2
ANT_COLLISION_CHECK_INTERVAL = FPS_LIMIT // 10

# FPS_LIMIT = 6

# PH_MAX_STRENGTH = 10
# ANT_TURN_INTERVAL = FPS_LIMIT
# PH_DROP_INTERVAL = FPS_LIMIT
# PH_DECAY_INTERVAL = FPS_LIMIT * 10
# ANT_COLLISION_CHECK_INTERVAL = FPS_LIMIT

PH_TYPES = ['home', 'food']
PH_COLORS = ['white', 'yellow']

# MAX_ANTS_PER_COLONY = 1
# MAX_ANTS_PER_COLONY = 5
# MAX_ANTS_PER_COLONY = 20
# MAX_ANTS_PER_COLONY = 50
MAX_ANTS_PER_COLONY = 200
# MAX_ANTS_PER_COLONY = 500
# MAX_ANTS_PER_COLONY = 1000

# SHOW_PHEROMONE_CHECK_MASKS = True
SHOW_PHEROMONE_CHECK_MASKS = False
